language: node_js
node_js:
    - "0.10"
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - node_modules/karma/bin/karma start test/karma.conf.js --single-run --browsers Firefox
after_success:
  - cat ./coverage/*/lcov.info | ./node_modules/coveralls/bin/coveralls.js
